const mongoose=require("mongoose");

const ClientSchema=mongoose.Schema({
    agent:{
        type:String,
        required:true
    },
    userType:{
        type:String,
        required:true,
        trim:true
    },
    policy_mode:{
        type:Number,
        required:true
    },
    producer:{
        type:String,
        required:true,
        trim:true
    },
    policy_number:{
        type:String,
        required:true
    },
    premium_amount_written:{
        type:Number
    },
    premium_amount:{
        type:Number,
        required:true

    },
    policy_type:{
        type:String,
        required:true,
        trim:true
    },
    company_name:{
        type:String,
        required:true,
        trim:true
    },
    category_name:{
        type:String,
        required:true,
        trim:true
    },
    policy_start_date:{
        type:Date,
        required:true
    },
    policy_end_date:{
        type:Date,
        required:true
    },
    csr:{
        type:String,
        required:true,
        trim:true
    },
    account_name:{
        type:String,
        required:true,
        trim:true
    },
    email:{
        type:String,
        required:true,
        trim:true
    },
    gender:{
        type:String,
        trim:true
    },
    firstname:{
        type:String,
        required:true,
        trim:true
    },
    city:{
        type:String,
        trim:true
    },
    account_type:{
        type:String,
        required:true,
        trim:true
    },
    phone:{
        type:String,
        required:true,
        trim:true
    },
    address:{
        type:String,
        trim:true
    },
    state:{
        type:String,
        trim:true
    },
    zip:{
        type:String,
        trim:true
    },
    dob:{
        type:Date,
        required:true
    },
    primary:{
        type:String,
        trim:true
    },
    Applicant_ID:{
        type:String,
        trim:true
    },
    agency_ID:{
        type:String,
        trim:true
    },
    hasActive_ClientPolicy:{
        type:String,
        trim:true
    }


},{strict:true});

module.exports=mongoose.model('Client',ClientSchema);
